### ISSUE TITLE
Combinatorial Output with Feedback Configuration for Simple Mode (mode 1) is not supported

### ISSUE THREAD

**Issue by skiselev** [daveho/GALasm#12]
According to [GAL16V8 datasheet](https://ece-classes.usc.edu/ee459/library/datasheets/16v8.pdf) pages 8 and 9, it should be possible to have feedback from an output pin in simple mode (galasm mode 1).
Unfortunately, it looks that galasm does not allow this.
If such configuration is attempted, it will switch to mode 2 (complex mode).

Here is a simple example showing this issue:

```
GAL16V8         ; first line : used GAL
FEEDBACK        ; second line: any text (max. 8 char.)

A       B       NC      NC      NC      NC      NC      NC      NC      GND
NC      NC      NC      NC      NC      NC      NC      D       C       VCC

C = /A
D = B * C


DESCRIPTION

This example shows a bug in galasm

According to GAL16V8 datasheet, it should be possible to have feedback
from an output pin in mode 1, but galasm does not allow this, and
will switch to mode 2 (complex mode) if it encounters any pin with feedback

```

**Comment by pjdennis** [comment]
I've looked through the proposed changes... it appears they might introduce a problem for GAL types other than GAL16V8 and GAL20V8. I added a more detailed comment at the code level.

**Comment by pjdennis** [comment]
Support for feedback in simple mode for GAL16V8 and GAL20V8 added via pull request #13.
